version: "3.8"
services:
  wiremock:
    ports:
      - "8443:8443"
    networks: 
      - dojo-network
    build: 
      context: ./stub
      dockerfile: Dockerfile
  
  dojo-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=IntegrationTest
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8081:80"
    networks: 
      - dojo-network
    build:
      context: ./src/Dojo.Api
      dockerfile: Dockerfile
    
networks: 
    dojo-network:
        driver: bridge