version: "3.3"
services:
  wiremock:
    ports:
      - "8443:8443"
    build: 
      context: ./stub
      dockerfile: Dockerfile
  
  dojo-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=IntegrationTest
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"
    build:
      context: ./src/Dojo.Api
      dockerfile: Dockerfile
